# Generated by Django 5.0.1 on 2024-01-30 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_authors_options_alter_books_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredients",
            name="pantry",
        ),
    ]
